#!/bin/zsh
# Profile file. Runs on login.

# Adds `~/.local/bin/` and all subdirectories to $PATH
export PATH="$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//'):$PATH"
# If Ndless wanted
# export PATH="$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//'):$PATH:/home/tiago/Documents/src/Ndless/ndless-sdk/toolchain/install/bin:/home/tiago/Documents/src/Ndless/ndless-sdk/bin"

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="brave"
export READER="zathura"
export FILE="lfub"

export SHELL="/bin/zsh"
export SUDO_ASKPASS="$HOME/.local/bin/tools/dmenupass"
export NOTMUCH_CONFIG="$HOME/.config/notmuch-config"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export SXHKD_SHELL="/bin/sh"

#ffsend
# export FFSEND_HOST="https://send.tteles.dev/"
# seriously, feel free to use it, I just don't want to get crawled into a pedo hub
# export FFSEND_BASIC_AUTH="insecure:feelfreetouse"


# Cleanup of home dir
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export PYTHONSTARTUP="$XDG_CONFIG_HOME"/python/pyrc.py
export npm_config_prefix="${XDG_DATA_HOME:-$HOME/.local/share}/node_modules"
export SCREENSHOTS="$HOME/Images/Screenshots"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

# less/man colors
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"; a="${a%_}"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"; a="${a%_}"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"; a="${a%_}"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"; a="${a%_}"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"; a="${a%_}"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"; a="${a%_}"

mpd >/dev/null 2>&1 &

[ ! -f ~/.config/shortcutrc ] && shortcuts >/dev/null 2>&1

echo "$0" | grep "bash$" >/dev/null && [ -f ~/.bashrc ] && source "$HOME/.bashrc"

# Switch escape and caps if tty:
sudo -n loadkeys ~/.local/bin/ttymaps.kmap 2>/dev/null

[ -f ~/.config/lf/icons ] && source ${XDG_CONFIG_HOME:-$HOME/.config}/lf/icons

# ndless-dev config
# export PATH="$PATH:/home/tiago/Documents/src/Ndless/ndless-sdk/toolchain/install/bin:/home/tiago/Documents/src/Ndless/ndless-sdk/bin"


export IDEA_JDK=/usr/lib/jvm/jre-jetbrains
export PHPSTORM_JDK=/usr/lib/jvm/jre-jetbrains
export WEBIDE_JDK=/usr/lib/jvm/jre-jetbrains
export PYCHARM_JDK=/usr/lib/jvm/jre-jetbrains
export RUBYMINE_JDK=/usr/lib/jvm/jre-jetbrains
export CL_JDK=/usr/lib/jvm/jre-jetbrains
export DATAGRIP_JDK=/usr/lib/jvm/jre-jetbrains
export GOLAND_JDK=/usr/lib/jvm/jre-jetbrains
export STUDIO_JDK=/usr/lib/jvm/jre-jetbrains


# Start graphical server if i3 not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

