#!/bin/sh

if [ -f "/etc/X11/xinit/xinitrc.d/50-systemd-user.sh" ]; then
	. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
fi

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

ssh-agent i3
