#!/bin/sh

setbg &		# Set the background
# Switch to PT keyboard layout with Caps as Mod/Escape
setxkbmap -option caps:super -layout pt && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
sxhkd &	# Bind keys
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & # load custom colors
# Properties button extra Mod/Escape
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
picom &		# compton for epic gamer effects
dunst &			# dunst for notifications
mpdupdate &
# mpd-mpris &
